version: '3'
services:
  api:
    image: node:12.18.4
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION=mongodb://publish-admin:publish-pass@db:27017
      - DB_NAME=posts
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=publish-admin
      - MONGO_INITDB_DATABASE=publish
      - MONGO_INITDB_ROOT_PASSWORD=publish-pass
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/:/docker-entrypoint-initdb.d/seed.js:ro"
volumes:
  dbdata:
